[General]
key_pmi=4565186564
key_pmi_invite_msg="Gaurav Gahlot is inviting you to a scheduled Zoom meeting.\r\n\r\nTopic: Gaurav Gahlot's Personal Meeting Room\r\n\r\nJoin Zoom Meeting\r\nhttps://us02web.zoom.us/j/4565186564?pwd=SUZEZm9LRTJ1dE51QzBkR01qNDlTdz09\r\n\r\nMeeting ID: 456 518 6564\r\nPasscode: Tszc33\r\n\r\n"
